### ISSUE TITLE
Performance heavy CSS selectors

### ISSUE THREAD

**Issue by MihajloLazar1** [db-ui/mono#2508]
### Which generators are impacted?

- [ ] All
- [ ] HTML
- [X] React
- [ ] Angular
- [ ] Vue
- [ ] Web components
- [ ] Power Apps

### Reproduction case

```jsx
// Test.tsx
import { ReactNode, useState } from 'react';
import 'src/assets/db-ui-42-rollup.css';

const elements: Array<ReactNode> = [];

for (let i = 0, l = 8600; i < l; i++) {
	elements.push(<div key={i}>element {i}</div>);
}

export const Test = () => {
	const [value, setValue] = useState('');

	return (
		<div>
			<textarea value={value} onChange={(e) => setValue(e.target.value)}></textarea>
			<div
				className="test"
				style={{ display: 'grid', gridTemplateColumns: 'repeat(240, 1fr)', gap: 10 }}
			>
				{elements}
			</div>
		</div>
	);
};

// main.tsx
import { createRoot } from 'react-dom/client';
import { Test } from 'src/Test';

// React18 application setup code (see https://reactjs.org/docs/hello-world.html)
const root = createRoot(document.getElementById('root')!);
root.render(<Test />);
```

### Expected Behaviour

No delays are expected when typing something into the textarea element.

### Browser version

None

### Add any other context about the problem here.

I managed to pinpoint the issue. I think it comes from the `/node_modules/@db-ui/components/build/components/page/page.scss` which generates this CSS code:

```css
:root:has(.fixed-header-footer) #app,
:root:has(.fixed-header-footer) #root,
:root:has(.fixed-header-footer) body,
:root:has(db-page[type=fixedHeaderFooter]) #app,
:root:has(db-page[type=fixedHeaderFooter]) #root,
:root:has(db-page[type=fixedHeaderFooter]) body {
	block-size: 100%
}
```

With this style, here is the performance snapshot while typing "asd" multiple times in the textarea:

![1](https://github.com/db-ui/mono/assets/161047514/faa72f4f-d739-49d1-bbec-4d6c72b0c682)

And if we adjust the generated CSS to something like this:

```css
:root:has(.fixed-header-footer) #app,
/*:root:has(.fixed-header-footer) #root,
:root:has(.fixed-header-footer) body,*/
:root:has(db-page[type=fixedHeaderFooter]) #app
/*:root:has(db-page[type=fixedHeaderFooter]) #root,
:root:has(db-page[type=fixedHeaderFooter]) body*/ {
	block-size: 100%
}
```

we get perfect performance (no delay) while typing in the textarea element. Here performance snapshot with the commented out CSS code: 

![2](https://github.com/db-ui/mono/assets/161047514/a9fa86d2-a768-4ab3-bc6b-1cdf25dcef5a)

I agree, we should not have that many DOM elements, but the issue appears with lower numbers as well.
Since there is a fix to it, would you please consider re-writing those selectors to be more performant?
