### ISSUE TITLE
Popover with no automation is placed incorrectly

### ISSUE THREAD

**Issue by flipswitchingmonkey** [db-ui/mono#3391]
### Which generators are impacted?

- [X] All
- [ ] HTML
- [ ] React
- [ ] Angular
- [ ] Vue
- [ ] Web components
- [ ] Power Apps

### Reproduction case

Just hover over the button with no animation at https://db-ui.github.io/mono/review/main/components/utilities/popover/overview

As a workaround, I'm using a custom CSS like so for the moment:

```css
.db-popover-content[data-animation='disabled'] {
  animation: popover-animation 0s normal both;
}
```

### Expected Behaviour

Should be centred like with animation

### Screenshots

![CleanShot_20241030_134735](https://github.com/user-attachments/assets/6475bd4a-f320-4b4c-85bf-42ec470624e7)

### Browser version

None
