### ISSUE TITLE
Text is displayed in light green on an invalid input element in dark mode

### ISSUE THREAD

**Issue by milan-w** [db-ui/mono#3502]
### Which generators are impacted?

- [ ] All
- [ ] HTML
- [X] React
- [ ] Angular
- [ ] Vue
- [ ] Web components
- [ ] Power Apps

### Reproduction case

Only tested it in React, might also affect other use cases.  
Repro:

- check out the db-ui-v3 branch on ri-react ;)
- create new quote or edit existing one
- set one field of form to invalid (no content or < 3 chars)

I think this CSS is not applied correctly, no idea where it is generated
```css
.db-input:has(input[data-custom-validity=invalid]) [id$=-placeholder], .db-input:has(input[data-custom-validity=invalid]) input {    
    caret-color: var(--db-successful-on-bg-basic-emphasis-100-default);    
    color: var(--db-successful-on-bg-basic-emphasis-100-default);
}
```

### Expected Behaviour

Text in invalid input field is displayed in a color that corresponds to it being invalid

### Screenshots

![image](https://github.com/user-attachments/assets/9384f3a7-1b3c-4ece-8d12-1382573b7a35)

### Browser version

None
